export enum ProductCategory {
  TABLES = 'TABLES',
  CHAIRS = 'CHAIRS',
  BEDS = 'BEDS',
  SHELVES = 'SHELVES',
  STORAGE = 'STORAGE',
  DESKS = 'DESKS',
  OUTDOOR = 'OUTDOOR',
  DECORATIVE = 'DECORATIVE'
}