services:
  postgres:
    image: postgres:15-alpine
    container_name: furnibles-postgres
    environment:
      POSTGRES_DB: furnibles
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: furnibles-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data: