/* eslint-disable */
/* prettier-ignore */

// WARNING: DO NOT EDIT THIS FILE
// This file is auto-generated by nestjs-i18n

import { Path } from 'nestjs-i18n';

export type I18nTranslations = {
  "auth": {
    "invalid_credentials": string;
    "unauthorized": string;
    "token_expired": string;
  };
  "common": {
    "success": string;
    "error": string;
    "not_found": string;
  };
  "emails": {
    "welcome": {
      "subject": string;
      "body": string;
    };
    "order_confirmation": {
      "subject": string;
      "body": string;
    };
  };
  "errors": {
    "validation": {
      "required": string;
      "email": string;
      "min_length": string;
    };
    "auth": {
      "invalid_token": string;
      "expired_token": string;
    };
  };
  "files": {
    "upload_success": string;
    "upload_error": string;
    "invalid_format": string;
  };
  "orders": {
    "created": string;
    "not_found": string;
    "cancelled": string;
    "completed": string;
  };
  "products": {
    "created": string;
    "updated": string;
    "deleted": string;
    "not_found": string;
    "approved": string;
    "rejected": string;
  };
  "test": {
    "hello": string;
  };
  "users": {
    "created": string;
    "updated": string;
    "not_found": string;
    "deactivated": string;
  };
  "validation": {
    "required": string;
    "email": string;
    "min_length": string;
    "max_length": string;
    "numeric": string;
  };
};

export type I18nPath = Path<I18nTranslations>;